version: "3.7"

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/

  app:
    depends_on: [ db ]
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "5500:5500"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
